name: Release
on:
  push:
    branches:
      - main
jobs:
  run_test_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run test and generate coverage
      run: yarn test:coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage/coverage-final.json
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
